"""create_spatiotemporal_atlas_tables

Revision ID: ae9ba2d3d645
Revises: 
Create Date: 2026-09-15 00:38:09.472142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.event


# revision identifiers, used by Alembic.
revision: str = 'ae9ba2d3d645'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('territorial_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('provider_url', sa.String(length=500), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('extraction_date', sa.DateTime(), nullable=True),
    sa.Column('reference_period_start', app.models.event.HistoricalDate(), nullable=True),
    sa.Column('reference_period_end', app.models.event.HistoricalDate(), nullable=True),
    sa.Column('methodology_summary', sa.Text(), nullable=True),
    sa.Column('methodology_url', sa.String(length=500), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('crs', sa.String(length=50), nullable=False),
    sa.Column('geometry_type', sa.String(length=50), nullable=True),
    sa.Column('feature_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('territorial_datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_territorial_datasets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorial_datasets_is_demo'), ['is_demo'], unique=False)

    op.create_table('region_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('geometry_geojson', sa.Text(), nullable=False),
    sa.Column('valid_from', app.models.event.HistoricalDate(), nullable=True),
    sa.Column('valid_to', app.models.event.HistoricalDate(), nullable=True),
    sa.Column('geometry_source', sa.String(length=255), nullable=True),
    sa.Column('location_precision', sa.String(length=50), nullable=False),
    sa.Column('is_anachronistic', sa.Boolean(), nullable=False),
    sa.Column('anachronism_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['territorial_datasets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('region_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_region_versions_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_region_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_region_versions_region_id'), ['region_id'], unique=False)

    op.create_table('event_footprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('geometry_geojson', sa.Text(), nullable=False),
    sa.Column('footprint_type', sa.String(length=50), nullable=False),
    sa.Column('location_precision', sa.String(length=50), nullable=False),
    sa.Column('buffer_meters', sa.Float(), nullable=True),
    sa.Column('region_version_id', sa.Integer(), nullable=True),
    sa.Column('coordinate_source', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_version_id'], ['region_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_footprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_footprints_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_footprints_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_footprints_region_version_id'), ['region_version_id'], unique=False)

    op.create_table('institutional_facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('facility_type', sa.String(length=50), nullable=False),
    sa.Column('region_version_id', sa.Integer(), nullable=True),
    sa.Column('geometry_geojson', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('opened_at', app.models.event.HistoricalDate(), nullable=True),
    sa.Column('closed_at', app.models.event.HistoricalDate(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['region_version_id'], ['region_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('institutional_facilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institutional_facilities_facility_type'), ['facility_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_institutional_facilities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_institutional_facilities_is_demo'), ['is_demo'], unique=False)
        batch_op.create_index(batch_op.f('ix_institutional_facilities_region_version_id'), ['region_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_institutional_facilities_source_id'), ['source_id'], unique=False)

    op.create_table('movement_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_type', sa.String(length=50), nullable=False),
    sa.Column('origin_geometry', sa.Text(), nullable=True),
    sa.Column('origin_region_version_id', sa.Integer(), nullable=True),
    sa.Column('destination_geometry', sa.Text(), nullable=True),
    sa.Column('destination_region_version_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('date_start', app.models.event.HistoricalDate(), nullable=True),
    sa.Column('date_end', app.models.event.HistoricalDate(), nullable=True),
    sa.Column('temporal_precision', sa.String(length=50), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('evidence_strength', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['destination_region_version_id'], ['region_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['origin_region_version_id'], ['region_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movement_flows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movement_flows_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movement_flows_destination_region_version_id'), ['destination_region_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movement_flows_flow_type'), ['flow_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_movement_flows_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movement_flows_is_demo'), ['is_demo'], unique=False)
        batch_op.create_index(batch_op.f('ix_movement_flows_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movement_flows_origin_region_version_id'), ['origin_region_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movement_flows_person_id'), ['person_id'], unique=False)

    with op.batch_alter_table('territorial_relation_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_territorial_relation_sources_id'))
        batch_op.drop_index(batch_op.f('ix_territorial_relation_sources_source_id'))
        batch_op.drop_index(batch_op.f('ix_territorial_relation_sources_territorial_relation_id'))

    op.drop_table('territorial_relation_sources')


    with op.batch_alter_table('territorial_relations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_version_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('temporal_precision', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('date_is_estimated', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('claim_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('evidence_strength', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('independent_root_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_contested', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('contested_by_claim_ids', sa.Text(), nullable=True))
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('relation_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('date_start',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.event.HistoricalDate(),
               nullable=True)
        batch_op.alter_column('date_end',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.event.HistoricalDate(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_territorial_relations_region_id'))
        batch_op.create_index(batch_op.f('ix_territorial_relations_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorial_relations_is_contested'), ['is_contested'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorial_relations_is_demo'), ['is_demo'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorial_relations_region_version_id'), ['region_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorial_relations_relation_type'), ['relation_type'], unique=False)
        batch_op.create_foreign_key('fk_territorial_relations_region_version_id', 'region_versions', ['region_version_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_territorial_relations_claim_id', 'claims', ['claim_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('region_id')
        batch_op.drop_column('confidence_level')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('territorial_relations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence_level', sa.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('region_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_territorial_relations_region_version_id', type_='foreignkey')
        batch_op.drop_constraint('fk_territorial_relations_claim_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_territorial_relations_regions_region_id', 'regions', ['region_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_territorial_relations_relation_type'))
        batch_op.drop_index(batch_op.f('ix_territorial_relations_region_version_id'))
        batch_op.drop_index(batch_op.f('ix_territorial_relations_is_demo'))
        batch_op.drop_index(batch_op.f('ix_territorial_relations_is_contested'))
        batch_op.drop_index(batch_op.f('ix_territorial_relations_claim_id'))
        batch_op.create_index(batch_op.f('ix_territorial_relations_region_id'), ['region_id'], unique=False)
        batch_op.alter_column('date_end',
               existing_type=app.models.event.HistoricalDate(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('date_start',
               existing_type=app.models.event.HistoricalDate(),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('relation_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('contested_by_claim_ids')
        batch_op.drop_column('is_contested')
        batch_op.drop_column('independent_root_count')
        batch_op.drop_column('evidence_strength')
        batch_op.drop_column('claim_id')
        batch_op.drop_column('date_is_estimated')
        batch_op.drop_column('temporal_precision')
        batch_op.drop_column('region_version_id')



    op.create_table('territorial_relation_sources',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('territorial_relation_id', sa.INTEGER(), nullable=False),
    sa.Column('source_id', sa.INTEGER(), nullable=False),
    sa.Column('page_or_section', sa.VARCHAR(length=100), nullable=True),
    sa.Column('excerpt', sa.TEXT(), nullable=False),
    sa.Column('validation_status', sa.VARCHAR(length=30), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['territorial_relation_id'], ['territorial_relations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('territorial_relation_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_territorial_relation_sources_territorial_relation_id'), ['territorial_relation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorial_relation_sources_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_territorial_relation_sources_id'), ['id'], unique=False)

    with op.batch_alter_table('movement_flows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movement_flows_person_id'))
        batch_op.drop_index(batch_op.f('ix_movement_flows_origin_region_version_id'))
        batch_op.drop_index(batch_op.f('ix_movement_flows_organization_id'))
        batch_op.drop_index(batch_op.f('ix_movement_flows_is_demo'))
        batch_op.drop_index(batch_op.f('ix_movement_flows_id'))
        batch_op.drop_index(batch_op.f('ix_movement_flows_flow_type'))
        batch_op.drop_index(batch_op.f('ix_movement_flows_destination_region_version_id'))
        batch_op.drop_index(batch_op.f('ix_movement_flows_claim_id'))

    op.drop_table('movement_flows')
    with op.batch_alter_table('institutional_facilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institutional_facilities_source_id'))
        batch_op.drop_index(batch_op.f('ix_institutional_facilities_region_version_id'))
        batch_op.drop_index(batch_op.f('ix_institutional_facilities_is_demo'))
        batch_op.drop_index(batch_op.f('ix_institutional_facilities_id'))
        batch_op.drop_index(batch_op.f('ix_institutional_facilities_facility_type'))

    op.drop_table('institutional_facilities')
    with op.batch_alter_table('event_footprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_footprints_region_version_id'))
        batch_op.drop_index(batch_op.f('ix_event_footprints_id'))
        batch_op.drop_index(batch_op.f('ix_event_footprints_event_id'))

    op.drop_table('event_footprints')
    with op.batch_alter_table('region_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_region_versions_region_id'))
        batch_op.drop_index(batch_op.f('ix_region_versions_id'))
        batch_op.drop_index(batch_op.f('ix_region_versions_dataset_id'))

    op.drop_table('region_versions')
    with op.batch_alter_table('territorial_datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_territorial_datasets_is_demo'))
        batch_op.drop_index(batch_op.f('ix_territorial_datasets_id'))

    op.drop_table('territorial_datasets')
    # ### end Alembic commands ###
